stages:
  - test
  - deploy

test_backend:
  stage: test
  image: python:3.9-slim
  script:
    - pip install -r requirements.txt
    - python manage.py test

deploy_to_production:
  stage: deploy
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t my-django-app .
    - docker push my-django-app

